# Generated by Django 2.2.3 on 2019-07-22 02:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hostel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostel_name', models.CharField(max_length=50)),
                ('total_rooms', models.IntegerField()),
                ('address', models.CharField(max_length=100)),
                ('created_on', models.DateField(auto_now=True)),
                ('updated_on', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mess_name', models.CharField(max_length=50)),
                ('created_on', models.DateField(auto_now=True)),
                ('updated_on', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_no', models.CharField(max_length=50)),
                ('created_on', models.DateField(auto_now=True)),
                ('updated_on', models.DateField(auto_now=True)),
                ('hostel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostelapp.Hostel')),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('post', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=15, null=True)),
                ('email', models.EmailField(default='', max_length=100)),
                ('created_on', models.DateField(auto_now=True)),
                ('updated_on', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('roll_no', models.IntegerField(unique=True)),
                ('email', models.EmailField(default='', max_length=100)),
                ('phone', models.CharField(max_length=15, null=True)),
                ('created_on', models.DateField(auto_now=True)),
                ('updated_on', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudentRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_occupied', models.BooleanField()),
                ('created_on', models.DateField(auto_now=True)),
                ('updated_on', models.DateField(auto_now=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostelapp.Room')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostelapp.Student')),
            ],
        ),
        migrations.CreateModel(
            name='HostelStaff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField()),
                ('hostel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostelapp.Hostel')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostelapp.Staff')),
            ],
        ),
    ]
